spring:
  application:
    name: knx_planner
  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/knx_planner
#    password: password
    username: lb3krr8sthid9h4m
    url: jdbc:mysql://lb3krr8sthid9h4m:f4hap9hvlx1x6atm@d6q8diwwdmy5c9k9.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/irgpxt85n4arkkk5
    password: f4hap9hvlx1x6atm
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          jdbc:
            lob:
              non_contextual_creation: 'true'
      hibernate:
        ddl-auto: none
      show-sql: false
jwt:
  secret: "replace-with-a-very-long-random-secret-at-least-32-chars"
  expiration-ms: 360000000
server:
  port: ${PORT:8080}